// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8lej0B1pzKafpJMXSnBM5OyS_B3rkG6g',
    appId: '1:773377368977:android:22fcad19352c9bc24cb030',
    messagingSenderId: '773377368977',
    projectId: 'space-vet-app',
    storageBucket: 'space-vet-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTwbPv-zW79v4l6EhvkwRFFwRC5ihwQQ4',
    appId: '1:773377368977:ios:5e2b74a869e7f6724cb030',
    messagingSenderId: '773377368977',
    projectId: 'space-vet-app',
    storageBucket: 'space-vet-app.firebasestorage.app',
    androidClientId: '773377368977-38t7nj7shtsubemhmhbhsddflqktsdio.apps.googleusercontent.com',
    iosClientId: '773377368977-co5fsuhs6ni37co3e1svnm0sm4relh9c.apps.googleusercontent.com',
    iosBundleId: 'com.example.spacevetApp',
  );
}
